SELECT TBL01.START_DATE
, TBL02.END_DATE

FROM(
(SELECT *,
 ROW_NUMBER() OVER (ORDER BY END_DATE DESC) AS RowNumber  

FROM(
SELECT END_DATE 
FROM Projects
WHERE END_DATE  NOT IN
(
SELECT START_DATE
FROM Projects
) 
) AS A) AS TBL02
JOIN 
(SELECT *,
 ROW_NUMBER() OVER (ORDER BY START_DATE DESC) AS RowNumber  

FROM(
SELECT START_DATE 
FROM Projects
WHERE START_DATE  NOT IN
(
SELECT END_DATE
FROM Projects
) 
) AS B) AS TBL01
ON TBL01.RowNumber=TBL02.RowNumber)
ORDER BY DATEDIFF(DAY,TBL01.START_DATE,TBL02.END_DATE) ,TBL01.START_DATE

